# Generated by Django 2.1.3 on 2018-11-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='descripe',
            new_name='description',
        ),
    ]
